class FoodstuffM{
  String title;

  FoodstuffM (this.title,);
}

final List<FoodstuffM> foods = [
  FoodstuffM('Творог 5%'),
  FoodstuffM('Яйца С1'),
  FoodstuffM('Рисовая мука'),
  FoodstuffM('Миндальная мука'),
  FoodstuffM('Руккола'),
  FoodstuffM('Бурый рис'),
  FoodstuffM('Топленое масло'),
  FoodstuffM('Лимонный сок'),
  FoodstuffM('Бананы'),
  FoodstuffM('Овсяные хлопья'),
  FoodstuffM('Репчатый лук'),
  FoodstuffM('Бульон'),
  FoodstuffM('Морковь'),
  FoodstuffM('Кабачки'),
  FoodstuffM('Болгарский перец'),
  FoodstuffM('Цельнозерновая рисовая мука'),
  FoodstuffM('Гречка'),
  FoodstuffM('Шампиньоны'),
  FoodstuffM('Вода'),
  FoodstuffM('Кокосовая стружка'),
  FoodstuffM('Малина'),
  FoodstuffM('Консервированный тунец в собственном соку'),
  FoodstuffM('Домашний майонез'),
  FoodstuffM('Каперсы'),
  FoodstuffM('Кальмары очищенные'),
  FoodstuffM('Помидоры'),
  FoodstuffM('Фета'),
  FoodstuffM('Петрушка'),
  FoodstuffM('Укроп'),
  FoodstuffM('Чеснок (зубчики)'),
  FoodstuffM('Мука из зеленой гречки'),
  FoodstuffM('Сливочное масло'),
  FoodstuffM('Разрыхлитель'),
  FoodstuffM('Корица'),
  FoodstuffM('Ваниль'),
  FoodstuffM('Cтевия'),
  FoodstuffM('Крахмал'),
  FoodstuffM('Нектарины'),
  FoodstuffM(''),
  FoodstuffM(''),
  FoodstuffM(''),
  FoodstuffM(''),
  FoodstuffM(''),
  FoodstuffM(''),
];